from datetime import datetime, timezone

from app.external_docs.extractor import ExternalDocsExtractor, _strip_generated_markup_noise
from app.external_docs.types import CrawledPage


def test_external_docs_extractor_removes_navigation_and_preserves_code() -> None:
    html = """
    <html>
      <head>
        <title>HTTP Request node</title>
        <link rel="canonical" href="https://docs.example.com/integrations/http-request" />
      </head>
      <body>
        <nav>Docs navigation should disappear</nav>
        <main>
          <h1>HTTP Request node</h1>
          <p>Use this node to call an API.</p>
          <pre><code>curl https://api.example.com/v1/items</code></pre>
          <table><tr><th>Name</th><td>Authorization</td></tr></table>
        </main>
        <footer>Footer should disappear</footer>
      </body>
    </html>
    """
    page = CrawledPage(
        source_name="docs",
        url="https://docs.example.com/integrations/http-request?ref=nav",
        html=html,
        status_code=200,
        content_type="text/html",
        fetched_at=datetime.now(timezone.utc),
    )

    extracted = ExternalDocsExtractor().extract(page)

    assert extracted.title == "HTTP Request node"
    assert extracted.canonical_url == "https://docs.example.com/integrations/http-request"
    assert "Docs navigation" not in extracted.structured_text
    assert "Footer should disappear" not in extracted.structured_text
    assert "Use this node to call an API." in extracted.structured_text
    assert "```" in extracted.structured_text
    assert "curl https://api.example.com/v1/items" in extracted.structured_text
    assert extracted.content_hash


def test_external_docs_extractor_removes_markdown_anchor_html_and_copy_buttons() -> None:
    html = """
    <html>
      <head><title>Install with npm</title></head>
      <body>
        <main>
          <h1>Install with npm</h1>
          <p>For the complete documentation index, see llms.txt.</p>
          <p>This page is also available as Markdown.</p>
          <p># Terminal 1 &lt;a href="#terminal-1" id="terminal-1"&gt;&lt;/a&gt;</p>
          <p>Run n8n locally.</p>
          <pre>Copy</pre>
          <pre><code>npm install n8n -g</code></pre>
        </main>
      </body>
    </html>
    """
    page = CrawledPage(
        source_name="docs",
        url="https://docs.example.com/deploy/install-with-npm",
        html=html,
        status_code=200,
        content_type="text/html",
        fetched_at=datetime.now(timezone.utc),
    )

    extracted = ExternalDocsExtractor().extract(page)

    assert '<a href="#terminal-1"' not in extracted.structured_text
    assert "id=\"terminal-1\"" not in extracted.structured_text
    assert "complete documentation index" not in extracted.structured_text
    assert "available as Markdown" not in extracted.structured_text
    assert "```\nCopy\n```" not in extracted.structured_text
    assert "npm install n8n -g" in extracted.structured_text


def test_external_docs_extractor_removes_generated_previous_next_footer_tail() -> None:
    html = """
    <html>
      <head><title>Credentials</title></head>
      <body>
        <main>
          <h1>Credentials</h1>
          <p>Credentials store authentication details for external services.</p>
          <p>Previous Model Selector Next Action Network credentials</p>
          <p>Last updated 7 days ago</p>
          <p>Was this helpful?</p>
          <ul>
            <li>Overview</li>
            <li>Setup</li>
          </ul>
        </main>
      </body>
    </html>
    """
    page = CrawledPage(
        source_name="docs",
        url="https://docs.example.com/credentials",
        html=html,
        status_code=200,
        content_type="text/html",
        fetched_at=datetime.now(timezone.utc),
    )

    extracted = ExternalDocsExtractor().extract(page)

    assert "Credentials store authentication details" in extracted.structured_text
    assert "Previous Model Selector" not in extracted.structured_text
    assert "Next Action Network" not in extracted.structured_text
    assert "Last updated" not in extracted.structured_text
    assert "Was this helpful" not in extracted.structured_text
    assert "- Overview" not in extracted.structured_text


def test_external_docs_extractor_removes_openrouter_generator_boilerplate_and_preserves_api_content() -> None:
    html = """
    <html>
      <head><title>OpenRouter API</title></head>
      <body>
        <main>
          <h1>OpenRouter API</h1>
          <p>For the complete documentation index, see llms.txt</p>
          <p>View as Markdown</p>
          <p>Generated by Mintlify</p>
          <p>Use the OpenAI-compatible API with /chat/completions and /api/v1/models.</p>
          <pre><code>curl https://openrouter.ai/api/v1/chat/completions
-H "Content-Type: application/json"</code></pre>
        </main>
      </body>
    </html>
    """
    page = CrawledPage(
        source_name="openrouter_docs",
        url="https://openrouter.ai/docs/api-reference/overview",
        html=html,
        status_code=200,
        content_type="text/html",
        fetched_at=datetime.now(timezone.utc),
    )

    extracted = ExternalDocsExtractor().extract(page)

    assert "llms.txt" not in extracted.structured_text
    assert "View as Markdown" not in extracted.structured_text
    assert "Generated by Mintlify" not in extracted.structured_text
    assert "/chat/completions" in extracted.structured_text
    assert "/api/v1/models" in extracted.structured_text
    assert "Content-Type: application/json" in extracted.structured_text


def test_external_docs_extractor_removes_telegram_page_chrome_and_preserves_method_docs() -> None:
    html = """
    <html>
      <head><title>Telegram Bot API</title></head>
      <body>
        <main>
          <p>Skip to content</p>
          <p>On this page</p>
          <p>&lt;div class="navigation"&gt;Navigation menu&lt;/div&gt;</p>
          <p>Cookie settings Accept all cookies</p>
          <h1>sendMessage</h1>
          <p>Use sendMessage to send text messages. Parameters include chat_id, parse_mode, and MessageEntity.</p>
          <p>HTML parse mode supports &lt;b&gt;bold&lt;/b&gt;, &lt;a href="https://example.com"&gt;links&lt;/a&gt;, and &lt;span class="tg-spoiler"&gt;spoilers&lt;/span&gt;.</p>
        </main>
      </body>
    </html>
    """
    page = CrawledPage(
        source_name="telegram_bot_api_docs",
        url="https://core.telegram.org/bots/api",
        html=html,
        status_code=200,
        content_type="text/html",
        fetched_at=datetime.now(timezone.utc),
    )

    extracted = ExternalDocsExtractor().extract(page)

    assert "Skip to content" not in extracted.structured_text
    assert "On this page" not in extracted.structured_text
    assert "Navigation menu" not in extracted.structured_text
    assert "Cookie settings" not in extracted.structured_text
    assert "Accept all cookies" not in extracted.structured_text
    assert "<div" not in extracted.structured_text
    assert "class=\"navigation\"" not in extracted.structured_text
    assert "sendMessage" in extracted.structured_text
    assert "chat_id" in extracted.structured_text
    assert "parse_mode" in extracted.structured_text
    assert "MessageEntity" in extracted.structured_text
    assert "<b>bold</b>" in extracted.structured_text
    assert "<a href=\"https://example.com\">links</a>" in extracted.structured_text


def test_external_docs_extractor_removes_telegram_template_markers_and_preserves_api_examples() -> None:
    """Keep synthetic Telegram evidence while removing page-template residue."""
    html = """
    <html>
      <head><title>Telegram Bot API methods</title></head>
      <body>
        <main>
          <p>&lt;div id="dev_page_image" data-template="telegram"&gt;&lt;/div&gt;</p>
          <p>Back to the Bot API Manual</p>
          <ul>
            <li>Bot API Manual</li>
            <li>Navigation menu</li>
          </ul>
          <p>&lt;script src="/assets/template.js" data-page="chrome"&gt;&lt;/script&gt;</p>
          <p>&lt;style data-page="chrome"&gt;&lt;/style&gt;</p>
          <h1>sendMessage</h1>
          <p>sendMessage sends text to chat_id. The parse_mode parameter is optional.</p>
          <p>MessageEntity describes formatting. Use setWebhook or getUpdates for incoming updates.</p>
          <p>InputFile uploads files through the Bot API endpoint.</p>
          <p>HTML formatting supports &lt;b&gt;bold&lt;/b&gt;, &lt;i&gt;italic&lt;/i&gt;, &lt;a href="https://example.com"&gt;links&lt;/a&gt;, and &lt;span class="tg-spoiler"&gt;spoilers&lt;/span&gt;.</p>
          <pre><code>curl -X POST https://api.telegram.org/botTOKEN/sendMessage \\
  -d chat_id=123 \\
  -d text=hello</code></pre>
        </main>
      </body>
    </html>
    """
    page = CrawledPage(
        source_name="telegram_bot_api_docs",
        url="https://core.telegram.org/bots/api",
        html=html,
        status_code=200,
        content_type="text/html",
        fetched_at=datetime.now(timezone.utc),
    )

    extracted = ExternalDocsExtractor().extract(page)

    assert "dev_page_image" not in extracted.structured_text
    assert "Back to the Bot API Manual" not in extracted.structured_text
    assert "Bot API Manual" not in extracted.structured_text
    assert "Navigation menu" not in extracted.structured_text
    assert "template.js" not in extracted.structured_text
    assert "data-page" not in extracted.structured_text
    assert "sendMessage" in extracted.structured_text
    assert "chat_id" in extracted.structured_text
    assert "parse_mode" in extracted.structured_text
    assert "MessageEntity" in extracted.structured_text
    assert "setWebhook" in extracted.structured_text
    assert "getUpdates" in extracted.structured_text
    assert "InputFile" in extracted.structured_text
    assert "optional" in extracted.structured_text
    assert "<b>bold</b>" in extracted.structured_text
    assert "<i>italic</i>" in extracted.structured_text
    assert "<a href=\"https://example.com\">links</a>" in extracted.structured_text
    assert "<span class=\"tg-spoiler\">spoilers</span>" in extracted.structured_text
    assert "```" in extracted.structured_text
    assert "https://api.telegram.org/botTOKEN/sendMessage" in extracted.structured_text


def test_generated_navigation_cleaning_preserves_prose_urls_and_code_fences() -> None:
    raw = "\n".join(
        [
            "# API guide",
            "",
            "Read the manual before configuring setWebhook.",
            "",
            "Back to the API Manual",
            "",
            "- API Manual",
            "",
            "Use https://docs.example.com/manual for the API reference.",
            "",
            "```text",
            "Back to the API Manual",
            "- API Manual",
            "```",
        ]
    )

    once = _strip_generated_markup_noise(raw)
    twice = _strip_generated_markup_noise(once)

    assert once == twice
    assert "Back to the API Manual" not in once.split("```text", 1)[0]
    assert "- API Manual" not in once.split("```text", 1)[0]
    assert "Read the manual before configuring setWebhook." in once
    assert "https://docs.example.com/manual" in once
    assert "```text\nBack to the API Manual\n- API Manual\n```" in once


def test_generated_markup_cleaning_is_idempotent_and_preserves_code_fences() -> None:
    raw = "\n".join(
        [
            "# Example",
            "",
            "View as Markdown",
            "",
            "```html",
            "<div class=\"example\">Keep this HTML example</div>",
            "```",
            "",
            "Use /api/v1/models in the request.",
        ]
    )

    once = _strip_generated_markup_noise(raw)
    twice = _strip_generated_markup_noise(once)

    assert once == twice
    assert "View as Markdown" not in once
    assert "<div class=\"example\">Keep this HTML example</div>" in once
    assert "/api/v1/models" in once
