"""Extract clean structured text from whitelisted external docs HTML."""

from __future__ import annotations

from datetime import datetime, timezone
from hashlib import sha256
from html.parser import HTMLParser
import re
from typing import Callable
from urllib.parse import urljoin

from app.external_docs.types import CrawledPage, ExtractedPage
from app.ingestion.text_normalizer import TextNormalizer, clean_heading

SKIP_TAGS = {"aside", "footer", "form", "header", "nav", "noscript", "script", "style", "svg"}
BLOCK_TAGS = {"h1", "h2", "h3", "h4", "h5", "h6", "p", "li", "td", "th"}
EMPTY_ANCHOR_RE = re.compile(r"\s*<a\b[^>]*>\s*</a>\s*", re.IGNORECASE)
COPY_ONLY_FENCE_RE = re.compile(r"```\s*Copy\s*```", re.IGNORECASE)
GENERATOR_BOILERPLATE_RE = re.compile(
    r"\bFor the complete documentation index,\s*see\s+llms\.txt\s*\.\s*"
    r"|\bThis page is also available as Markdown\s*\.\s*",
    re.IGNORECASE,
)
PREVIOUS_NEXT_NAV_RE = re.compile(r"\bPrevious\b.+\bNext\b", re.IGNORECASE)
FOOTER_START_RE = re.compile(r"^(?:Last updated\b.*|Was this helpful\??)$", re.IGNORECASE)
STANDALONE_NAVIGATION_RETURN_RE = re.compile(
    r"^(?:back\s+to|return\s+to|go\s+back\s+to)\s+(?:the\s+)?"
    r"(?P<destination>(?:[A-Za-z0-9-]+\s+){0,5}(?:manual|documentation|docs|guide|reference))$",
    re.IGNORECASE,
)
LIST_ITEM_PREFIX_RE = re.compile(r"^(?:[-*]\s+|\d+[.)]\s+)")
GENERATOR_CHROME_LINE_RE = re.compile(
    r"\b(?:llms\.txt|available as markdown|view as markdown|generated by mintlify|powered by mintlify)\b",
    re.IGNORECASE,
)
NAVIGATION_CHROME_LINE_RE = re.compile(
    r"\b(?:skip to content|on this page|table of contents|navigation menu|"
    r"cookie banner|cookie settings|accept all cookies|manage cookies|privacy policy|terms of service)\b",
    re.IGNORECASE,
)
RAW_PAGE_TAG_RE = re.compile(
    r"</?(?P<tag>html|body|div|span|script|style|nav|footer|header|aside|main|section|article|button|ul|ol|li)\b(?P<attrs>[^>]*)>",
    re.IGNORECASE,
)
TG_SPOILER_SPAN_RE = re.compile(r"<span\b[^>]*\btg-spoiler\b[^>]*>.*?</span>", re.IGNORECASE | re.DOTALL)

class ExternalDocsExtractor:
    """Convert fetched HTML pages into clean structured text."""

    def extract(self, page: CrawledPage) -> ExtractedPage:
        """Extract page title, canonical URL, headings, and body text."""
        parser = _HtmlTextParser(base_url=page.url)
        parser.feed(page.html)
        title = clean_heading(parser.title, fallback=_title_from_url(page.url))
        canonical_url = parser.canonical_url or page.url
        blocks = parser.blocks
        if title and (not blocks or blocks[0] != f"# {title}"):
            blocks = [f"# {title}", *blocks]
        structured_text = TextNormalizer().normalize(_strip_generated_markup_noise("\n\n".join(blocks)))
        content_hash = _content_hash(title=title, canonical_url=canonical_url, structured_text=structured_text)
        return ExtractedPage(
            source_name=page.source_name,
            source_url=page.url,
            canonical_url=canonical_url,
            title=title,
            structured_text=structured_text,
            content_hash=content_hash,
            headings=tuple(parser.headings),
            crawled_at=page.fetched_at or datetime.now(timezone.utc),
            metadata={
                "status_code": page.status_code,
                "content_type": page.content_type,
                "depth": page.depth,
            },
        )


class _HtmlTextParser(HTMLParser):
    def __init__(self, *, base_url: str) -> None:
        super().__init__(convert_charrefs=True)
        self.base_url = base_url
        self.title = ""
        self.canonical_url = ""
        self.headings: list[str] = []
        self.blocks: list[str] = []
        self._skip_depth = 0
        self._tag_stack: list[str] = []
        self._buffer: list[str] = []
        self._title_buffer: list[str] = []
        self._code_buffer: list[str] = []
        self._in_title = False
        self._in_pre = False

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        tag = tag.lower()
        attrs_dict = {key.lower(): value for key, value in attrs}
        if tag in SKIP_TAGS:
            self._skip_depth += 1
            return
        if self._skip_depth:
            return
        if tag == "link" and (attrs_dict.get("rel") or "").lower() == "canonical" and attrs_dict.get("href"):
            self.canonical_url = urljoin(self.base_url, str(attrs_dict["href"]))
            return
        if tag == "title":
            self._in_title = True
            self._title_buffer = []
            return
        if tag == "pre":
            self._flush_text()
            self._in_pre = True
            self._code_buffer = []
            return
        if tag in BLOCK_TAGS:
            self._flush_text()
            self._tag_stack.append(tag)
        elif tag == "br":
            self._append("\n")

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()
        if tag in SKIP_TAGS and self._skip_depth:
            self._skip_depth -= 1
            return
        if self._skip_depth:
            return
        if tag == "title":
            self._in_title = False
            self.title = _clean_inline(" ".join(self._title_buffer))
            return
        if tag == "pre" and self._in_pre:
            code = "\n".join(line.rstrip() for line in "".join(self._code_buffer).splitlines()).strip()
            if code and code.casefold() != "copy":
                self.blocks.append(f"```\n{code}\n```")
            self._code_buffer = []
            self._in_pre = False
            return
        if self._tag_stack and tag == self._tag_stack[-1]:
            self._flush_text(tag=self._tag_stack.pop())

    def handle_data(self, data: str) -> None:
        if self._skip_depth:
            return
        if self._in_title:
            self._title_buffer.append(data)
            return
        if self._in_pre:
            self._code_buffer.append(data)
            return
        self._append(data)

    def _append(self, text: str) -> None:
        if text:
            self._buffer.append(text)

    def _flush_text(self, tag: str | None = None) -> None:
        text = _clean_inline(" ".join(self._buffer))
        self._buffer = []
        if not text:
            return
        if tag and tag.startswith("h") and tag[1:].isdigit():
            level = min(max(int(tag[1:]), 1), 6)
            heading = clean_heading(text, fallback="")
            if heading:
                self.headings.append(heading)
                self.blocks.append(f"{'#' * level} {heading}")
            return
        if tag == "li":
            self.blocks.append(f"- {text}")
            return
        self.blocks.append(text)


def _clean_inline(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def _strip_generated_markup_noise(text: str) -> str:
    """Remove docs-generator markup that is not useful evidence."""
    cleaned = _outside_fenced_code(text or "", _strip_inline_markup_noise)
    cleaned = _outside_fenced_code(cleaned, lambda value: EMPTY_ANCHOR_RE.sub(" ", value))
    cleaned = _outside_fenced_code(cleaned, lambda value: COPY_ONLY_FENCE_RE.sub(" ", value))
    cleaned = _outside_fenced_code(cleaned, lambda value: GENERATOR_BOILERPLATE_RE.sub(" ", value))
    return _strip_generated_navigation_tail(cleaned)


def _strip_generated_navigation_tail(text: str) -> str:
    """Remove generic docs navigation/footer blocks from extracted text."""
    lines: list[str] = []
    dropping_footer = False
    in_code = False
    pending_navigation_destination = ""
    for line in str(text or "").splitlines():
        clean = _clean_inline(line)
        if clean.startswith("```"):
            lines.append(line)
            in_code = not in_code
            continue
        if in_code:
            lines.append(line)
            continue
        if dropping_footer:
            continue
        navigation_destination = _standalone_navigation_destination(clean)
        if navigation_destination:
            pending_navigation_destination = navigation_destination
            continue
        if pending_navigation_destination and clean:
            if _is_related_navigation_label(clean, pending_navigation_destination):
                pending_navigation_destination = ""
                continue
            pending_navigation_destination = ""
        if clean and FOOTER_START_RE.match(clean):
            dropping_footer = True
            continue
        if clean and (
            PREVIOUS_NEXT_NAV_RE.search(clean)
            or GENERATOR_CHROME_LINE_RE.search(clean)
            or NAVIGATION_CHROME_LINE_RE.search(clean)
        ):
            continue
        lines.append(line)
    return "\n".join(lines)


def _standalone_navigation_destination(line: str) -> str:
    """Return a short navigation destination from a standalone chrome line."""
    match = STANDALONE_NAVIGATION_RETURN_RE.fullmatch(line)
    if not match:
        return ""
    return _clean_inline(match.group("destination")).casefold()


def _is_related_navigation_label(line: str, destination: str) -> bool:
    """Match the immediate list label that duplicates a navigation destination."""
    label = LIST_ITEM_PREFIX_RE.sub("", line).casefold()
    return label == destination


def _strip_inline_markup_noise(text: str) -> str:
    """Strip escaped page-template HTML while keeping useful inline HTML examples."""
    protected_spans: list[str] = []

    def _protect_tg_spoiler(match: re.Match[str]) -> str:
        protected_spans.append(match.group(0))
        return f"@@TG_SPOILER_SPAN_{len(protected_spans) - 1}@@"

    def _replace_tag(match: re.Match[str]) -> str:
        del match
        return " "

    cleaned = TG_SPOILER_SPAN_RE.sub(_protect_tg_spoiler, text)
    cleaned = RAW_PAGE_TAG_RE.sub(_replace_tag, cleaned)
    for index, value in enumerate(protected_spans):
        cleaned = cleaned.replace(f"@@TG_SPOILER_SPAN_{index}@@", value)
    return cleaned


def _outside_fenced_code(text: str, transform: Callable[[str], str]) -> str:
    """Apply a text transform outside fenced code blocks."""
    result: list[str] = []
    buffer: list[str] = []
    in_code = False
    for line in str(text or "").splitlines(keepends=True):
        if line.lstrip().startswith("```"):
            if buffer:
                result.append(transform("".join(buffer)))
                buffer = []
            result.append(line)
            in_code = not in_code
            continue
        if in_code:
            result.append(line)
        else:
            buffer.append(line)
    if buffer:
        result.append(transform("".join(buffer)))
    return "".join(result)


def _title_from_url(url: str) -> str:
    slug = url.rstrip("/").rsplit("/", 1)[-1]
    return slug.replace("-", " ").replace("_", " ").strip() or "External documentation"


def _content_hash(*, title: str, canonical_url: str, structured_text: str) -> str:
    digest = sha256()
    for value in (title, canonical_url, structured_text):
        digest.update(b"\0")
        digest.update(value.encode("utf-8", errors="replace"))
    return digest.hexdigest()
